### ISSUE TITLE
Shop not working, "Failed to load script @qb-core/shared.lua" + Question

### ISSUE THREAD

**Issue by ch0sguy** [swkeep/keep-hunting#2] opened 2022-02-09 03:52 UTC
Shop NPC isn't spawning for QB Target, attempted to manually add an NPC into QB Target and the shop still doesn't open, I've added all the necessary items into items.lua in qbcore shared.

Also, would it be possible to add functionality to where every animal on the map can be hunted and interacted with using QB-target, not just animals spawned via the baiting script?

EDIT: I've added a way to keep the player hunting at all times, just only able to bait in the zones; however, I was toying around with the config and I set alert police to 100 percent guarantee, and even in the legal hunting zones, the police are getting notified?

**Comment by swkeep** [comment] 2022-02-09 07:26
Hi, I would like to ask which shop? because one of them doesn't have an NPC! if I remember it correctly, I didn't add it to have less impact on other mods I might be able to add it if I find a way around it.

and about animals interaction with "QB-target" I agree with you and designed it that way but if it's not working like that I will be happy to have more information about it.

I did not fully implement police (i just forgot it ^.^)

**Comment by ch0sguy** [comment] 2022-02-09 07:57
The shop that you say to add into the qb-shops/config.lua file in your README, I've added both fields and nothing seemed to spawn at the location of the coords? 
![huntingshop](https://user-images.githubusercontent.com/62267705/153144868-2adf9c00-069b-4806-8799-111f638a9b23.PNG)

I even went into qb-target and added a custom NPC and gave him the role of opening qb-shops:marketshop, and for whatever reason, that npc doesn't open the shop either, but gives a prompt to when you interact with him
![qbtarget](https://user-images.githubusercontent.com/62267705/153146074-580914f5-5e35-4897-9564-20aa35ed94c8.PNG)
![shopdoesntopen](https://user-images.githubusercontent.com/62267705/153146238-cfa8f9bd-cf1e-4a26-8cd9-26930db0ff42.PNG)
In the image listed above, it shows the shop as an option, but nothing happens when selected.

Also, I added a new bool field next to inzone in client.lua, and I just said it to globally true, allowing the player the freedom to interact and skin every animal they kill in the world, regardless of being in the zone or not, but I only allow players in the zone to use bait.

**Comment by swkeep** [comment] 2022-02-09 10:08
there will be a slight issue if your hunting config doesn't match shops config I will try to fix it if possible.

**Comment by ch0sguy** [comment] 2022-02-09 20:36
I've added the new qb-shops server.lua edits and it still doesn't seem to work on my end? I'm also still getting the "failed to load qb-core/shared.lua" when i do "ensure "keep-hunting"; also, in what way does the hunting.config and shops.config need to match?

**Comment by ch0sguy** [comment] 2022-02-09 22:09
Is the shop system working on your end?

**Comment by swkeep** [comment] 2022-02-10 04:48
shop works fine for me.
I made an update and removed necessity of modifying QB-shops config file and dependency on @qb-core/shared.lua it should work fine without them and on a fresh install. 
If the problem still exists on your end after a fresh install of hunting script we can get into discord so I can see your changes, files, etc.

**Comment by ch0sguy** [comment] 2022-02-10 07:32
What exactly did you change/remove to get rid of the qb-core/shared.lua dependency, I assume it was the qb-shops input, correct? I would update to the newest version that you've released but I've already modified this one quite a bit, and would like to avoid doing that if necessary lol.

**Comment by swkeep** [comment] 2022-02-10 07:53
yes, in new version it can create NPC and shop by itself.
don't update/replace your script this might break yours, just add it with a new name and then test it.

**Comment by ch0sguy** [comment] 2022-02-11 03:28
Hey so I've been looking into the script a bit with other people on a test server, seems like multiple people can look the same animal after it is killed, as well as the animals don't disappear immediately, or for everyone, when skinned/butchered; sometimes they vanish instantly, so only that player gets the chance to skin them, whereas other they stay a lot longer, so everyone can skin them and get loot.

**Comment by swkeep** [comment] 2022-02-11 05:32
Hi, so players can skin/butchered animals multiple times? if they do it at the same time?
do they get loot even after this message "Someone already slaughtered this animal!"?

Edit: I think this is caused by how script is deleting animals. I will work on a solution to sync it.

**Comment by ch0sguy** [comment] 2022-02-11 05:39
I'm not seeing any notification of "Someone already slaughtered this animal!" for some reason, if it isn't happening with you then I will redownload and try again?

**Comment by swkeep** [comment] 2022-02-11 05:49
so because I know something like this might happen I added a function to force delete animals. but it's doesn't seem to work for some reason I will see what I can do.
(it was on the first version and I never modified it so you don't need to update it for now)

**Comment by swkeep** [comment] 2022-02-14 09:51
I will close this issue, it should be fixed right now.

**Closed by swkeep** 2022-02-14 09:51 UTC
Labels: bug
